[package]
name = "dynosol-svd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
reqwest = "0.12.23"
serde = "1.0.219"
serde_json = "1.0.143"
sqlx = { version = "0.8.6", features = ["postgres"] }
tokio = { version = "1.47.1", features = ["full"] }
