[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
refinery = { workspace = true }
dotenv = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
